# Generated by Django 6.0.1 on 2026-03-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_factory_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='starting_factory_space',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='player',
            name='factory_space',
            field=models.IntegerField(default=150),
        ),
    ]
