# Generated by Django 6.0.1 on 2026-03-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_difficulty_starting_factory_space_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='net_income',
            new_name='Cost_of_Goods_Sold',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='total_cost',
            new_name='gross_profit',
        ),
    ]
