# Generated by Django 6.0.1 on 2026-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_net_income_turn_cost_of_goods_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='rent_cost',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='net_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='operating_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
