# Generated by Django 6.0.1 on 2026-03-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_difficulty_rent_cost_turn_net_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
