# Generated by Django 6.0.1 on 2026-03-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_turn_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='factory_space_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
