# Generated by Django 6.0.1 on 2026-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_player_factory_space_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='company_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
