# Generated by Django 6.0.1 on 2026-03-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoutcome',
            name='demand_boost_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='AdvertisingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost_schedule', models.JSONField(default=list, help_text='Demand boost multipliers by turn offset. e.g. [1.0, 0.5, 0.25] means 100% boost turn 1, 50% turn 2, 25% turn 3, then zero.')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(default='Advertising Campaign', max_length=100)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_profiles', to='game.difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on_turn', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='game.player')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.advertisingprofile')),
            ],
        ),
    ]
