# Generated by Django 6.0.1 on 2026-03-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_productionoutcome_demand_boost_applied_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapitalInvestment',
        ),
    ]
