# Generated by Django 6.0.1 on 2026-03-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_delete_capitalinvestment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('premium_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disaster_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_distribution_json', models.JSONField(default=list, help_text='Discrete probability distribution for demand (6 steps)')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductionOutcome',
            new_name='ToyProductionOutcome',
        ),
        migrations.CreateModel(
            name='InsuranceEventOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_roll', models.IntegerField()),
                ('disaster_cost_realized', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_active', models.BooleanField(default=False)),
                ('premium_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.insuranceevent')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_decisions', to='game.turn')),
            ],
        ),
    ]
