# Generated by Django 6.0.1 on 2026-03-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_insuranceevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='ad_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='disaster_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='premium_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='demand_distribution_json',
            field=models.JSONField(default=list, help_text='cost of insurance disaster (6 sided dice)'),
        ),
    ]
