# Generated by Django 6.0.1 on 2026-03-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_turn_ad_cost_turn_disaster_cost_turn_premium_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='expansion_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='total_capex',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
