# Generated by Django 6.0.1 on 2026-03-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_turn_expansion_cost_turn_total_capex'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='free_cash_flow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
