# Generated by Django 6.0.1 on 2026-04-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_player_cost_savings_coefficient_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='equipment_bought',
            field=models.BooleanField(default=False),
        ),
    ]
