# Generated by Django 6.0.1 on 2026-04-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_equipment_bought_remove_equipment_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cost_savings_coefficient',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12),
        ),
    ]
