# Generated by Django 6.0.1 on 2026-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_player_cost_savings_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cost_savings_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
