# Generated by Django 6.0.1 on 2026-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_player_cost_savings_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='equipment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
