# Generated by Django 6.0.1 on 2026-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_turn_equipment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='equipment_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
