# Generated by Django 6.0.1 on 2026-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_player_equipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='beginning_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='ending_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
