# Generated by Django 6.0.1 on 2026-04-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_turn_beginning_cash_turn_ending_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
