# Generated by Django 6.0.1 on 2026-04-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_difficulty_tax_rate_turn_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
