# Generated by Django 6.0.1 on 2026-04-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_turn_depreciation_turn_other_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='EBITDA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='EBT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
