# Generated by Django 6.0.1 on 2026-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_turn_ebitda_turn_ebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='useful_life',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='depreciation_expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='depreciation_expense_ends_turn',
            field=models.IntegerField(default=0),
        ),
    ]
