# Generated by Django 6.0.1 on 2026-05-11 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_equipment_useful_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_length', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_leverage_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_amount_available_to_borrow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_available_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('player_able_to_borrow', models.BooleanField(default=False)),
                ('money_borrowed_this_turn', models.BooleanField(default=False)),
                ('money_borrowed_on_turn', models.IntegerField(default=0)),
                ('amount_borrowed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_begin_turn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_end_turn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_year', models.IntegerField(default=0)),
                ('principal_payment_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_payment_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
