# Generated by Django 6.0.1 on 2026-05-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='max_leverage_ratio',
        ),
    ]
