# Generated by Django 6.0.1 on 2026-05-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_remove_loan_max_leverage_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='max_leverage_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
