# Generated by Django 6.0.1 on 2026-07-06 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_loan_max_leverage_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy_Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='basket', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='difficulty',
            old_name='factory_space_cost',
            new_name='factory_space_cost_coefficient',
        ),
        migrations.RenameField(
            model_name='difficulty',
            old_name='winning_cash',
            new_name='winning_networth',
        ),
        migrations.AddField(
            model_name='difficulty',
            name='ads_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='equipment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='financing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='insurance_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='intercept_doll',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='intercept_racecar',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='min_years_of_financial_history',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='new_product_success_b',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='new_product_success_cost_coefficient',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='peak_doll',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='rnd_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='slope_doll',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='slope_racecar',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cumulative_rnd_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='next_offered_rate',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=6),
        ),
        migrations.AddField(
            model_name='player',
            name='total_equity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='unlocked_toy_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='toy',
            name='default_toy',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='accumulated_depreciation_equipment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='change_in_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='financing_cf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='gross_equipment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='gross_ppe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='interest_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='interest_tax_shield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='investing_cf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='loan_proceeds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='loans_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='new_product_produced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turn',
            name='new_product_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='new_product_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='operating_cf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='principal_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='property',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='rnd_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turn',
            name='total_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='InterestRateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Rate', max_length=100)),
                ('rate_distribution_json', models.JSONField(default=list, help_text='List of [rate, weight] pairs. e.g. [[0.07, 20], [0.10, 50], [0.13, 30]]')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_profiles', to='game.difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on_turn', models.IntegerField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('loan_length', models.IntegerField()),
                ('annual_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid_off', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='toy_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.toy_basket'),
        ),
        migrations.AddField(
            model_name='toy',
            name='toy_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='game.toy_basket'),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
