# Generated by Django 6.0.1 on 2026-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_loan_max_leverage_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='ads_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='equipment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='financing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='insurance_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
