# Generated by Django 6.0.1 on 2026-06-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_difficulty_ads_enabled_difficulty_equipment_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on_turn', models.IntegerField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('loan_length', models.IntegerField()),
                ('annual_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid_off', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='game.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
