# Generated by Django 6.0.1 on 2026-07-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_toy_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='toy_pick_options_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='turn',
            name='toy_pick_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
