# Generated by Django 6.0.1 on 2026-08-03 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_turn_toy_pick_options_json_turn_toy_pick_roll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mode',
            field=models.CharField(choices=[('freeplay', 'Freeplay'), ('challenge', 'Challenge Mode')], default='freeplay', max_length=10),
        ),
        migrations.CreateModel(
            name='ChallengeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='None', max_length=100)),
                ('lives_total', models.IntegerField(default=3)),
                ('lives_remaining', models.IntegerField(default=3)),
                ('time_limit_seconds', models.IntegerField(default=6300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('won', 'Won'), ('lost_lives', 'Lost - Out of Lives'), ('lost_timeout', 'Lost - Out of Time')], default='in_progress', max_length=20)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.difficulty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='challenge_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.challengerun'),
        ),
    ]
