# Generated by Django 6.0.1 on 2026-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_playerloan_delete_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
    ]
