# Generated by Django 6.0.1 on 2026-08-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_player_mode_challengerun_player_challenge_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='show_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
