# Generated by Django 6.0.1 on 2026-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_remove_player_min_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='min_years_of_financial_history',
            field=models.IntegerField(default=3),
        ),
    ]
