# Generated by Django 6.0.1 on 2026-06-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_rename_winning_cash_difficulty_winning_networth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='retained_earnings',
            new_name='total_equity',
        ),
    ]
