# Generated by Django 6.0.1 on 2026-06-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_rename_retained_earnings_player_total_equity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Rate', max_length=100)),
                ('rate_distribution_json', models.JSONField(default=list, help_text='List of [rate, weight] pairs. e.g. [[0.07, 20], [0.10, 50], [0.13, 30]]')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_profiles', to='game.difficulty')),
            ],
        ),
    ]
