# Generated by Django 6.0.1 on 2026-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_interestrateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_offered_rate',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=6),
        ),
    ]
