# Generated by Django 6.0.1 on 2026-06-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_player_next_offered_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='interest_tax_shield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
