# Generated by Django 6.0.1 on 2026-06-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_turn_interest_tax_shield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='difficulty',
            old_name='factory_space_cost',
            new_name='factory_space_cost_coefficient',
        ),
    ]
