# Generated by Django 6.0.1 on 2026-06-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_rename_factory_space_cost_difficulty_factory_space_cost_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='rnd_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='new_product_completed_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_product_completed_distribution', models.JSONField(default=list, help_text='List of [spend, weight] pairs. e.g. [[0.07, 20], [0.10, 50], [0.13, 30]]')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_and_development', to='game.difficulty')),
            ],
        ),
    ]
