# Generated by Django 6.0.1 on 2026-06-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_difficulty_rnd_enabled_new_product_completed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductSuccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('b', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_sucess_profile', to='game.difficulty')),
            ],
        ),
        migrations.DeleteModel(
            name='new_product_completed_profile',
        ),
    ]
