# Generated by Django 6.0.1 on 2026-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_newproductsuccessprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductsuccessprofile',
            name='m',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
