# Generated by Django 6.0.1 on 2026-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_alter_newproductsuccessprofile_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductsuccessprofile',
            name='name',
            field=models.CharField(default='New Product Success', max_length=100),
        ),
    ]
