# Generated by Django 6.0.1 on 2026-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_newproductsuccessprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='new_product_success_b',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='new_product_success_cost_coefficient',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='NewProductSuccessProfile',
        ),
    ]
