# Generated by Django 6.0.1 on 2026-06-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_difficulty_new_product_success_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cumulative_rnd_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
