# Generated by Django 6.0.1 on 2026-06-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_player_cumulative_rnd_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='rnd_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
