# Generated by Django 6.0.1 on 2026-06-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_turn_rnd_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='new_product_produced',
            field=models.BooleanField(default=False),
        ),
    ]
