# Generated by Django 6.0.1 on 2026-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0048_turn_new_product_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='new_product_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='new_product_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
