# Generated by Django 6.0.1 on 2026-06-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_turn_new_product_roll_turn_new_product_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='intercept_doll',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='intercept_racecar',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='peak_doll',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='slope_doll',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='slope_racecar',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
    ]
