# Generated by Django 6.0.1 on 2026-06-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_difficulty_intercept_doll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='toy_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='unlocked_toy_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
