# Generated by Django 6.0.1 on 2026-07-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_player_toy_unlocked_player_unlocked_toy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy_Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='basket', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='toy',
            name='enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='toy_basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.toy_basket'),
        ),
    ]
