# Generated by Django 6.0.1 on 2026-07-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_toy_basket_toy_enabled_toy_toy_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.toy_basket'),
        ),
    ]
