# Generated by Django 6.0.1 on 2026-07-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0053_alter_toy_toy_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='toy_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.toy_basket'),
        ),
    ]
