# Generated by Django 6.0.1 on 2026-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_alter_toy_toy_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
