# Generated by Django 6.0.1 on 2026-07-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_alter_toy_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='default_toy',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
